name: Submit your VoIP Provider report
description: Report a GOOD VoIP Provider
title: "[Replace this with the name of the provider]"
labels: ["vendor report"]
body:

  - type: markdown
    attributes:
      value: |
        If you haven't already, please view the official [Carrier Guide](https://www.empiresec.co/voip). 
        
        Want to dig into supporting your favourite carrier on some messaging app see [Soprani's Wiki](https://wiki.soprani.ca/).

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: For updates or changes, comment on the existing reports. Check for existing issues to prevent duplicates. 
      options:
        - label: I have searched the existing issues
          required: true

  - type: input
    id: country
    attributes:
      label: Country of the Vendor
      description: Specify what country the vendor is for (it is assumed you're using it in the same country here)
      placeholder: UK
    validations:
      required: true

  - type: input
    id: country_code
    attributes:
      label: Country Code of the Vendor
      description: Specify what country Code the vendor is for (it is assumed you're using it in the same country here)
      placeholder: "+44"
    validations:
      required: true

  - type: input
    id: vendor_name
    attributes:
      label: Vendor name
      description: What is the Vendor called?
      placeholder: Vonage
    validations:
      required: true

  - type: input
    id: signup_link
    attributes:
      label: Link to Vendor's Signup URL
      description: Paste the signup link
      placeholder: https://ui.idp.vonage.com/ui/auth/registration
    validations:
      required: true
      
  - type: input
    id: pricing
    attributes:
      label: Link to Vendor's Pricing
      description: Paste the pricing link
      placeholder: https://www.vonage.co.uk/communications-apis/pricing/
    validations:
      required: true
      
  - type: dropdown
    id: stars
    attributes:
      label: How many stars will you give the service?
      description: How many stars will you give the service?
      multiple: false
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
    validations:
        required: true
        
  - type: input
    id: thirdparty
    attributes:
      label: Any Link to 3rd Party reviewing the vendor (trustpilot/consumer reports/any blog etc..)
      description: Paste the link
      placeholder: https://www.trustpilot.com/review/www.vonage.co.uk
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description of the Vendor's functionality
      description: |
        What happens when you use the vendor? What tasks do work and don't work? What is the expected outcome of each thing you do? Did you test any other configurations and setups? Please mention all the steps to reproduce any issues. Do not leave out any information.

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

  - type: textarea
    id: extra_notes
    attributes:
      label: Are there any extra notes you think users should know about?
      description: |
        Did you do any workarounds other users should know that aren't listed here?

        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this report. Please keep tabs on it in case we get back to you.
